"""Add FisherCluster model

Revision ID: 06a4126b521d
Revises: bf76f89a252b
Create Date: 2026-06-18 11:59:11.666726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a4126b521d'
down_revision: Union[str, Sequence[str], None] = 'bf76f89a252b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fisher_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cluster_type', sa.Enum('artisanal', 'commercial', 'aquaculture', 'aggregator', 'mixed', name='clustertype'), nullable=False),
    sa.Column('cluster_status', sa.Enum('active', 'pending', 'verified', 'suspended', 'inactive', name='clusterstatus'), nullable=False),
    sa.Column('landing_site', sa.String(length=50), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('bmu_name', sa.String(length=100), nullable=True),
    sa.Column('bmu_registration_number', sa.String(length=50), nullable=True),
    sa.Column('species_specialization', sa.String(length=200), nullable=True),
    sa.Column('gear_types', sa.String(length=200), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('min_members', sa.Integer(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('weekly_capacity_kg', sa.Float(), nullable=True),
    sa.Column('monthly_capacity_kg', sa.Float(), nullable=True),
    sa.Column('avg_catch_per_trip_kg', sa.Float(), nullable=True),
    sa.Column('active_vessels', sa.Integer(), nullable=True),
    sa.Column('savings_balance_kes', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.Float(), nullable=True),
    sa.Column('total_earnings_kes', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('kebs_compliant', sa.Boolean(), nullable=True),
    sa.Column('has_iuu_training', sa.Boolean(), nullable=True),
    sa.Column('cluster_leader_name', sa.String(length=100), nullable=True),
    sa.Column('cluster_leader_phone', sa.String(length=20), nullable=True),
    sa.Column('cluster_leader_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_leader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fisher_clusters_cluster_code'), 'fisher_clusters', ['cluster_code'], unique=True)
    op.create_index(op.f('ix_fisher_clusters_cluster_status'), 'fisher_clusters', ['cluster_status'], unique=False)
    op.create_index(op.f('ix_fisher_clusters_id'), 'fisher_clusters', ['id'], unique=False)
    op.create_index(op.f('ix_fisher_clusters_landing_site'), 'fisher_clusters', ['landing_site'], unique=False)
    op.create_index(op.f('ix_fisher_clusters_name'), 'fisher_clusters', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fisher_clusters_name'), table_name='fisher_clusters')
    op.drop_index(op.f('ix_fisher_clusters_landing_site'), table_name='fisher_clusters')
    op.drop_index(op.f('ix_fisher_clusters_id'), table_name='fisher_clusters')
    op.drop_index(op.f('ix_fisher_clusters_cluster_status'), table_name='fisher_clusters')
    op.drop_index(op.f('ix_fisher_clusters_cluster_code'), table_name='fisher_clusters')
    op.drop_table('fisher_clusters')
    # ### end Alembic commands ###
