"""baseline sync after ESG fix

Revision ID: 3b587bff513e
Revises: f3c5a40f4c92
Create Date: 2026-05-11 16:05:20.358964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b587bff513e'
down_revision: Union[str, Sequence[str], None] = 'f3c5a40f4c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_distance_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_distance_km')
    # ### end Alembic commands ###
