"""Add PaymentTransaction model

Revision ID: 410fae6317b6
Revises: c8c731420c36
Create Date: 2026-05-14 11:30:09.047367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410fae6317b6'
down_revision: Union[str, Sequence[str], None] = 'c8c731420c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_reference', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payer_user_id', sa.Integer(), nullable=True),
    sa.Column('payee_user_id', sa.Integer(), nullable=True),
    sa.Column('payment_direction', sa.Enum('inbound', 'outbound', name='paymentdirection'), nullable=False),
    sa.Column('payment_purpose', sa.Enum('order_payment', 'deposit', 'final_settlement', 'refund', 'fisher_payout', 'advance_payment', 'logistics_payment', 'storage_payment', 'credit_settlement', name='paymentpurpose'), nullable=False),
    sa.Column('payment_channel', sa.Enum('mpesa', 'bank', 'cash', 'card', 'credit', 'crypto', name='paymentchannel'), nullable=False),
    sa.Column('payment_method', sa.Enum('mpesa_stk', 'mpesa_paybill', 'mpesa_b2c', 'bank_transfer', 'cash', 'card_online', 'credit_terms', 'crypto_future', name='paymentmethod'), nullable=False),
    sa.Column('payment_provider', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('subtotal_amount', sa.Float(), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=True),
    sa.Column('storage_fee_amount', sa.Float(), nullable=True),
    sa.Column('handling_fee_amount', sa.Float(), nullable=True),
    sa.Column('qa_fee_amount', sa.Float(), nullable=True),
    sa.Column('logistics_fee_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'processing', 'authorized', 'partially_paid', 'paid', 'failed', 'expired', 'refunded', 'reversed', 'on_credit', name='paymentstatus'), nullable=False),
    sa.Column('is_credit_sale', sa.Boolean(), nullable=False),
    sa.Column('credit_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credit_status', sa.Enum('not_applicable', 'pending_approval', 'approved', 'overdue', 'settled', 'defaulted', name='creditstatus'), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('credit_limit_snapshot', sa.Float(), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('mpesa_phone_number', sa.String(length=20), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('merchant_request_id', sa.String(length=100), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('gateway_reference', sa.String(length=100), nullable=True),
    sa.Column('supplier_amount', sa.Float(), nullable=True),
    sa.Column('marinecatch_amount', sa.Float(), nullable=True),
    sa.Column('payout_status', sa.Enum('not_applicable', 'pending', 'processing', 'paid', 'failed', 'on_hold', name='payoutstatus'), nullable=True),
    sa.Column('payout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_reference', sa.String(length=100), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('blockchain_tx_hash', sa.String(length=200), nullable=True),
    sa.Column('wallet_address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_mpesa_receipt_number'), 'payment_transactions', ['mpesa_receipt_number'], unique=False)
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_status'), 'payment_transactions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_transaction_reference'), 'payment_transactions', ['transaction_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_transactions_transaction_reference'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_mpesa_receipt_number'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
