"""Add trade_receivables and supplier_payments tables

Revision ID: 44c6252bac63
Revises: c760f4cebfe9
Create Date: 2026-06-24 13:56:14.143437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c6252bac63'
down_revision: Union[str, Sequence[str], None] = 'c760f4cebfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
