"""Add Organization model and organization_id to users

Revision ID: 4ed3edd63c8b
Revises: 7989d7a3a22e
Create Date: 2026-06-22 14:19:41.746213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ed3edd63c8b'
down_revision: Union[str, Sequence[str], None] = '7989d7a3a22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('trading_name', sa.String(length=150), nullable=True),
    sa.Column('org_type', sa.Enum('processor', 'exporter', 'hotel', 'restaurant', 'wholesaler', 'aggregator', 'retailer', 'fisher_coop', 'system', name='orgtype'), nullable=False),
    sa.Column('org_tier', sa.Enum('free', 'standard', 'enterprise', 'api_partner', 'system', name='orgtier'), nullable=False),
    sa.Column('org_status', sa.Enum('active', 'pending', 'verified', 'suspended', 'inactive', name='orgstatus'), nullable=False),
    sa.Column('primary_contact_name', sa.String(length=100), nullable=True),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=True),
    sa.Column('primary_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('kra_pin', sa.String(length=50), nullable=True),
    sa.Column('kebs_number', sa.String(length=50), nullable=True),
    sa.Column('subscription_plan', sa.String(length=30), nullable=False),
    sa.Column('subscription_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_fee_kes', sa.Float(), nullable=True),
    sa.Column('api_access_enabled', sa.Boolean(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=200), nullable=True),
    sa.Column('api_rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('data_sharing_consent', sa.Boolean(), nullable=False),
    sa.Column('can_see_market_prices', sa.Boolean(), nullable=False),
    sa.Column('inventory_visibility', sa.String(length=20), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_spend_kes', sa.Float(), nullable=True),
    sa.Column('total_kg_purchased', sa.Float(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_org_code'), 'organizations', ['org_code'], unique=True)
    op.create_index(op.f('ix_organizations_org_status'), 'organizations', ['org_status'], unique=False)
    op.create_index(op.f('ix_organizations_org_tier'), 'organizations', ['org_tier'], unique=False)
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'buyer_type',
               existing_type=postgresql.ENUM('institutional', 'retail', name='buyertype'),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'buyer_type',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('institutional', 'retail', name='buyertype'),
               existing_nullable=True)
    op.drop_column('users', 'organization_id')
    op.drop_index(op.f('ix_organizations_org_tier'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_org_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_org_code'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
