"""Add geography intelligence layer

Revision ID: 528324f9d589
Revises: dd2d8e06a1e7
Create Date: 2026-08-12 01:57:00.263942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528324f9d589'
down_revision: Union[str, Sequence[str], None] = 'dd2d8e06a1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_geography',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('geography_type', sa.String(length=50), nullable=False),
    sa.Column('official_name', sa.String(length=200), nullable=False),
    sa.Column('administrative_code', sa.String(length=50), nullable=True),
    sa.Column('centroid_latitude', sa.Float(), nullable=True),
    sa.Column('centroid_longitude', sa.Float(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_geography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_geography_country_code'), 'admin_geography', ['country_code'], unique=False)
    op.create_index(op.f('ix_admin_geography_geography_type'), 'admin_geography', ['geography_type'], unique=False)
    op.create_table('geographic_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_entity_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geography_source_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('claim_field', sa.String(length=100), nullable=False),
    sa.Column('claim_value', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('is_canonical', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geography_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('issuing_organization', sa.String(length=200), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('geographic_scope', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('reliability_tier', sa.Integer(), nullable=False),
    sa.Column('extracted_date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jcm_as',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marine_management_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('year_established', sa.Integer(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('no_take_status', sa.String(length=10), nullable=True),
    sa.Column('management_authority', sa.String(length=200), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('market_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_corridors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_validated', sa.String(length=10), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bmus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_name', sa.String(length=200), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('sub_county_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('headquarters_location', sa.String(length=200), nullable=True),
    sa.Column('registration_status', sa.String(length=50), nullable=True),
    sa.Column('active_status', sa.String(length=30), nullable=True),
    sa.Column('membership_count', sa.Integer(), nullable=True),
    sa.Column('fisher_count', sa.Integer(), nullable=True),
    sa.Column('boat_count', sa.Integer(), nullable=True),
    sa.Column('trader_count', sa.Integer(), nullable=True),
    sa.Column('women_members', sa.Integer(), nullable=True),
    sa.Column('youth_members', sa.Integer(), nullable=True),
    sa.Column('governance_status', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['admin_geography.id'], ),
    sa.ForeignKeyConstraint(['sub_county_id'], ['admin_geography.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['admin_geography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bmus_official_name'), 'bmus', ['official_name'], unique=False)
    op.create_table('bmu_jcma',
    sa.Column('bmu_id', sa.Integer(), nullable=False),
    sa.Column('jcma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bmu_id'], ['bmus.id'], ),
    sa.ForeignKeyConstraint(['jcma_id'], ['jcm_as.id'], ),
    sa.PrimaryKeyConstraint('bmu_id', 'jcma_id')
    )
    op.create_table('fish_landing_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_name', sa.String(length=200), nullable=False),
    sa.Column('local_name', sa.String(length=200), nullable=True),
    sa.Column('county_id', sa.Integer(), nullable=True),
    sa.Column('sub_county_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('locality_id', sa.Integer(), nullable=True),
    sa.Column('bmu_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('gazetted_status', sa.String(length=30), nullable=True),
    sa.Column('operational_status', sa.String(length=30), nullable=True),
    sa.Column('landing_type', sa.String(length=50), nullable=True),
    sa.Column('marine_environment', sa.String(length=50), nullable=True),
    sa.Column('beach_type', sa.String(length=50), nullable=True),
    sa.Column('estimated_fisher_count', sa.Integer(), nullable=True),
    sa.Column('estimated_boat_count', sa.Integer(), nullable=True),
    sa.Column('estimated_daily_volume_kg', sa.Float(), nullable=True),
    sa.Column('infrastructure_grade', sa.String(length=20), nullable=True),
    sa.Column('cold_storage_available', sa.Boolean(), nullable=True),
    sa.Column('ice_available', sa.Boolean(), nullable=True),
    sa.Column('electricity_available', sa.Boolean(), nullable=True),
    sa.Column('water_available', sa.Boolean(), nullable=True),
    sa.Column('road_access', sa.Boolean(), nullable=True),
    sa.Column('road_condition', sa.String(length=30), nullable=True),
    sa.Column('boat_repair', sa.Boolean(), nullable=True),
    sa.Column('gear_repair', sa.Boolean(), nullable=True),
    sa.Column('fish_banda', sa.Boolean(), nullable=True),
    sa.Column('toilets', sa.Boolean(), nullable=True),
    sa.Column('fish_processing', sa.Boolean(), nullable=True),
    sa.Column('fish_drying', sa.Boolean(), nullable=True),
    sa.Column('waste_management', sa.Boolean(), nullable=True),
    sa.Column('market_access', sa.Boolean(), nullable=True),
    sa.Column('mobile_network', sa.Boolean(), nullable=True),
    sa.Column('internet_connectivity', sa.Boolean(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bmu_id'], ['bmus.id'], ),
    sa.ForeignKeyConstraint(['county_id'], ['admin_geography.id'], ),
    sa.ForeignKeyConstraint(['locality_id'], ['admin_geography.id'], ),
    sa.ForeignKeyConstraint(['sub_county_id'], ['admin_geography.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['admin_geography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fish_landing_sites_official_name'), 'fish_landing_sites', ['official_name'], unique=False)
    op.create_table('fishing_grounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('local_name', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('associated_bmu_id', sa.Integer(), nullable=True),
    sa.Column('habitat', sa.String(length=100), nullable=True),
    sa.Column('depth_range', sa.String(length=50), nullable=True),
    sa.Column('target_species', sa.String(length=300), nullable=True),
    sa.Column('gear_types', sa.String(length=200), nullable=True),
    sa.Column('seasonal_usage', sa.String(length=100), nullable=True),
    sa.Column('fishing_pressure', sa.String(length=30), nullable=True),
    sa.Column('protected_status', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['associated_bmu_id'], ['bmus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mma_bmu',
    sa.Column('mma_id', sa.Integer(), nullable=False),
    sa.Column('bmu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bmu_id'], ['bmus.id'], ),
    sa.ForeignKeyConstraint(['mma_id'], ['marine_management_areas.id'], ),
    sa.PrimaryKeyConstraint('mma_id', 'bmu_id')
    )
    op.create_table('cold_chain_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_site_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('temperature_range', sa.String(length=50), nullable=True),
    sa.Column('ownership', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=150), nullable=True),
    sa.Column('operational_status', sa.String(length=30), nullable=True),
    sa.Column('energy_source', sa.String(length=50), nullable=True),
    sa.Column('species_supported', sa.String(length=300), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['landing_site_id'], ['fish_landing_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_site_id', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('verified_by_name', sa.String(length=150), nullable=True),
    sa.Column('verified_boat_count', sa.Integer(), nullable=True),
    sa.Column('verified_fisher_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['landing_site_id'], ['fish_landing_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_site_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.String(length=100), nullable=True),
    sa.Column('ownership', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=150), nullable=True),
    sa.Column('operational_status', sa.String(length=30), nullable=True),
    sa.Column('installation_year', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['landing_site_id'], ['fish_landing_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landing_site_fishing_grounds',
    sa.Column('landing_site_id', sa.Integer(), nullable=False),
    sa.Column('fishing_ground_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fishing_ground_id'], ['fishing_grounds.id'], ),
    sa.ForeignKeyConstraint(['landing_site_id'], ['fish_landing_sites.id'], ),
    sa.PrimaryKeyConstraint('landing_site_id', 'fishing_ground_id')
    )
    op.create_table('landing_site_markets',
    sa.Column('landing_site_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['landing_site_id'], ['fish_landing_sites.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('landing_site_id', 'market_id')
    )
    op.create_table('logistics_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_site_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['landing_site_id'], ['fish_landing_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_commercial_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_site_id', sa.Integer(), nullable=False),
    sa.Column('supply_volume_score', sa.Float(), nullable=True),
    sa.Column('species_diversity_score', sa.Float(), nullable=True),
    sa.Column('high_value_species_score', sa.Float(), nullable=True),
    sa.Column('buyer_demand_score', sa.Float(), nullable=True),
    sa.Column('cold_chain_score', sa.Float(), nullable=True),
    sa.Column('logistics_access_score', sa.Float(), nullable=True),
    sa.Column('fisher_density_score', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('sustainability_risk_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['landing_site_id'], ['fish_landing_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_investment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_site_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_kes', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['landing_site_id'], ['fish_landing_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_site_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('species_name_raw', sa.String(length=150), nullable=True),
    sa.Column('average_volume_kg', sa.Float(), nullable=True),
    sa.Column('peak_volume_kg', sa.Float(), nullable=True),
    sa.Column('minimum_volume_kg', sa.Float(), nullable=True),
    sa.Column('catch_frequency', sa.String(length=50), nullable=True),
    sa.Column('catch_method', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['landing_site_id'], ['fish_landing_sites.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
   
    op.create_table('supply_corridor_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=False),
    sa.Column('landing_site_id', sa.Integer(), nullable=True),
    sa.Column('node_name', sa.String(length=200), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_travel_time_min', sa.Integer(), nullable=True),
    sa.Column('transport_cost_kes', sa.Float(), nullable=True),
    sa.Column('refrigeration_required', sa.String(length=10), nullable=True),
    sa.Column('road_quality', sa.String(length=30), nullable=True),
    sa.Column('seasonal_accessibility', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['supply_corridors.id'], ),
    sa.ForeignKeyConstraint(['landing_site_id'], ['fish_landing_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species_seasonality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_availability_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('expected_availability', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('historical_basis', sa.String(length=200), nullable=True),
    sa.Column('observed_date', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['species_availability_id'], ['species_availability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species_seasonality')
    op.drop_table('supply_corridor_nodes')
    op.drop_table('species_availability')
    op.drop_table('site_investment_scores')
    op.drop_table('site_commercial_scores')
    op.drop_table('logistics_nodes')
    op.drop_table('landing_site_markets')
    op.drop_table('landing_site_fishing_grounds')
    op.drop_table('infrastructure_assets')
    op.drop_table('field_verifications')
    op.drop_table('cold_chain_assets')
    op.drop_table('mma_bmu')
    op.drop_table('fishing_grounds')
    op.drop_index(op.f('ix_fish_landing_sites_official_name'), table_name='fish_landing_sites')
    op.drop_table('fish_landing_sites')
    op.drop_table('bmu_jcma')
    op.drop_index(op.f('ix_bmus_official_name'), table_name='bmus')
    op.drop_table('bmus')
    op.drop_table('supply_corridors')
    op.drop_table('markets')
    op.drop_table('marine_management_areas')
    op.drop_table('jcm_as')
    op.drop_table('geography_sources')
    op.drop_table('geography_source_claims')
    op.drop_table('geographic_aliases')
    op.drop_index(op.f('ix_admin_geography_geography_type'), table_name='admin_geography')
    op.drop_index(op.f('ix_admin_geography_country_code'), table_name='admin_geography')
    op.drop_table('admin_geography')
    # ### end Alembic commands ###
