"""Add lot_id to orders, fisherman_id nullable

Revision ID: 5db0873ce667
Revises: 3b587bff513e
Create Date: 2026-05-13 10:17:02.559462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db0873ce667'
down_revision: Union[str, Sequence[str], None] = '3b587bff513e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('lot_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'fisherman_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_orders_lot_id'), 'orders', ['lot_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'inventory_lots', ['lot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_lot_id'), table_name='orders')
    op.alter_column('orders', 'fisherman_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'lot_id')
    # ### end Alembic commands ###
