"""Add settlement account fields to users

Revision ID: 89c716ba392d
Revises: 410fae6317b6
Create Date: 2026-05-17 22:25:48.373757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c716ba392d'
down_revision: Union[str, Sequence[str], None] = '410fae6317b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('settlement_account_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('settlement_account_type', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('settlement_account_verified', sa.Boolean(), nullable=False, server_default='false'))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settlement_account_verified')
    op.drop_column('users', 'settlement_account_type')
    op.drop_column('users', 'settlement_account_id')
    # ### end Alembic commands ###
