"""Add logistics models — DeliveryZone, FulfillmentHub, LogisticsProvider, Shipment

Revision ID: abd2eb9604e6
Revises: 89c716ba392d
Create Date: 2026-05-18 14:31:22.197756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd2eb9604e6'
down_revision: Union[str, Sequence[str], None] = '89c716ba392d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('zone_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('counties', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'coming_soon', 'not_served', 'suspended', name='zonestatus'), nullable=False),
    sa.Column('min_order_kg', sa.Float(), nullable=True),
    sa.Column('min_order_value_kes', sa.Float(), nullable=True),
    sa.Column('base_delivery_fee_kes', sa.Float(), nullable=True),
    sa.Column('per_kg_fee_kes', sa.Float(), nullable=True),
    sa.Column('estimated_delivery_days', sa.Integer(), nullable=True),
    sa.Column('same_day_available', sa.Boolean(), nullable=False),
    sa.Column('cold_chain_supported', sa.Boolean(), nullable=False),
    sa.Column('max_transit_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_code')
    )
    op.create_index(op.f('ix_delivery_zones_id'), 'delivery_zones', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_zones_zone_name'), 'delivery_zones', ['zone_name'], unique=True)
    op.create_table('logistics_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('provider_code', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('has_refrigerated_vehicles', sa.Boolean(), nullable=True),
    sa.Column('serves_zones', sa.String(length=500), nullable=True),
    sa.Column('base_rate_kes', sa.Float(), nullable=True),
    sa.Column('per_km_rate_kes', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code')
    )
    op.create_index(op.f('ix_logistics_providers_id'), 'logistics_providers', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_providers_provider_name'), 'logistics_providers', ['provider_name'], unique=False)
    op.create_table('fulfillment_hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_name', sa.String(length=100), nullable=False),
    sa.Column('hub_code', sa.String(length=20), nullable=False),
    sa.Column('hub_type', sa.Enum('marinecatch_owned', 'partner_hub', 'collection_point', 'landing_site', 'export_facility', name='hubtype'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('operator_user_id', sa.Integer(), nullable=True),
    sa.Column('operator_name', sa.String(length=100), nullable=True),
    sa.Column('operator_phone', sa.String(length=20), nullable=True),
    sa.Column('has_cold_storage', sa.Boolean(), nullable=False),
    sa.Column('cold_storage_capacity_kg', sa.Float(), nullable=True),
    sa.Column('can_dispatch', sa.Boolean(), nullable=False),
    sa.Column('can_receive', sa.Boolean(), nullable=False),
    sa.Column('serves_zones', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hub_code')
    )
    op.create_index(op.f('ix_fulfillment_hubs_hub_name'), 'fulfillment_hubs', ['hub_name'], unique=True)
    op.create_index(op.f('ix_fulfillment_hubs_id'), 'fulfillment_hubs', ['id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_reference', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('origin_hub_id', sa.Integer(), nullable=True),
    sa.Column('destination_zone_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'picked_up', 'in_transit', 'at_hub', 'out_for_delivery', 'delivered', 'failed', 'returned', name='shipmentstatus'), nullable=False),
    sa.Column('delivery_address', sa.String(length=300), nullable=True),
    sa.Column('delivery_contact_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('estimated_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_distance_km', sa.Float(), nullable=True),
    sa.Column('delivery_cost_kes', sa.Float(), nullable=True),
    sa.Column('fuel_cost_kes', sa.Float(), nullable=True),
    sa.Column('driver_fee_kes', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('temperature_min_celsius', sa.Float(), nullable=True),
    sa.Column('temperature_max_celsius', sa.Float(), nullable=True),
    sa.Column('temperature_threshold', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('humidity_min_percent', sa.Float(), nullable=True),
    sa.Column('humidity_max_percent', sa.Float(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cold_chain_status', sa.Enum('intact', 'breach', 'warning', 'unknown', name='coldchainstatus'), nullable=True),
    sa.Column('cold_chain_breach_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('door_open_count', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.String(length=100), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('driver_phone', sa.String(length=20), nullable=True),
    sa.Column('vehicle_reg', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receiver_name', sa.String(length=100), nullable=True),
    sa.Column('receiver_signature', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_zone_id'], ['delivery_zones.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['origin_hub_id'], ['fulfillment_hubs.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['logistics_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_id'), 'shipments', ['id'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_reference'), 'shipments', ['shipment_reference'], unique=True)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_reference'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_fulfillment_hubs_id'), table_name='fulfillment_hubs')
    op.drop_index(op.f('ix_fulfillment_hubs_hub_name'), table_name='fulfillment_hubs')
    op.drop_table('fulfillment_hubs')
    op.drop_index(op.f('ix_logistics_providers_provider_name'), table_name='logistics_providers')
    op.drop_index(op.f('ix_logistics_providers_id'), table_name='logistics_providers')
    op.drop_table('logistics_providers')
    op.drop_index(op.f('ix_delivery_zones_zone_name'), table_name='delivery_zones')
    op.drop_index(op.f('ix_delivery_zones_id'), table_name='delivery_zones')
    op.drop_table('delivery_zones')
    # ### end Alembic commands ###
