"""Create users fish_listings orders tables

Revision ID: b352c6ff247e
Revises: 
Create Date: 2026-05-10 12:34:46.469637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b352c6ff247e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FISHER', 'SUPPLIER', 'BUYER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('fish_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fisher_id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('available_kg', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('total_value_kes', sa.Float(), nullable=False),
    sa.Column('landing_site', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.Enum('FRESH', 'FROZEN', 'DRIED', 'PROCESSED', 'LIVE', name='fishcondition'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('harvest_date', sa.String(length=20), nullable=True),
    sa.Column('boat_number', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fisher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fish_listings_fisher_id'), 'fish_listings', ['fisher_id'], unique=False)
    op.create_index(op.f('ix_fish_listings_id'), 'fish_listings', ['id'], unique=False)
    op.create_index(op.f('ix_fish_listings_is_available'), 'fish_listings', ['is_available'], unique=False)
    op.create_index(op.f('ix_fish_listings_landing_site'), 'fish_listings', ['landing_site'], unique=False)
    op.create_index(op.f('ix_fish_listings_species'), 'fish_listings', ['species'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('fisherman_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('MARKETPLACE', 'PROCUREMENT', 'FULFILLMENT', name='ordertype'), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('landing_site', sa.String(length=50), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('total_kes', sa.Float(), nullable=False),
    sa.Column('platform_fee_kes', sa.Float(), nullable=False),
    sa.Column('net_to_fisher_kes', sa.Float(), nullable=False),
    sa.Column('commission_rate', sa.String(length=10), nullable=False),
    sa.Column('delivery_address', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DISPATCHED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fisherman_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['fish_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_orders_fisherman_id'), 'orders', ['fisherman_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_fisherman_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_fish_listings_species'), table_name='fish_listings')
    op.drop_index(op.f('ix_fish_listings_landing_site'), table_name='fish_listings')
    op.drop_index(op.f('ix_fish_listings_is_available'), table_name='fish_listings')
    op.drop_index(op.f('ix_fish_listings_id'), table_name='fish_listings')
    op.drop_index(op.f('ix_fish_listings_fisher_id'), table_name='fish_listings')
    op.drop_table('fish_listings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
