"""Add fisheries data models — Species, LandingSite, HistoricalLanding

Revision ID: bb7ce0014f0c
Revises: 4ed3edd63c8b
Create Date: 2026-06-23 22:23:22.361203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7ce0014f0c'
down_revision: Union[str, Sequence[str], None] = '4ed3edd63c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('bmu_name', sa.String(length=100), nullable=True),
    sa.Column('bmu_registration', sa.String(length=50), nullable=True),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('sub_county', sa.String(length=50), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('active_fishers', sa.Integer(), nullable=True),
    sa.Column('active_vessels', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_landing_sites_id'), 'landing_sites', ['id'], unique=False)
    op.create_index(op.f('ix_landing_sites_name'), 'landing_sites', ['name'], unique=False)
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=150), nullable=True),
    sa.Column('local_name', sa.String(length=100), nullable=True),
    sa.Column('family', sa.String(length=100), nullable=True),
    sa.Column('category', sa.Enum('demersal', 'pelagic', 'crustacean', 'mollusc', 'elasmobranch', 'other', name='fishcategory'), nullable=False),
    sa.Column('avg_price_per_kg_kes', sa.Float(), nullable=True),
    sa.Column('min_price_per_kg_kes', sa.Float(), nullable=True),
    sa.Column('max_price_per_kg_kes', sa.Float(), nullable=True),
    sa.Column('peak_months', sa.String(length=50), nullable=True),
    sa.Column('iucn_status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_common_name'), 'species', ['common_name'], unique=False)
    op.create_index(op.f('ix_species_id'), 'species', ['id'], unique=False)
    op.create_index(op.f('ix_species_local_name'), 'species', ['local_name'], unique=False)
    op.create_table('historical_landings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('landing_site_id', sa.Integer(), nullable=True),
    sa.Column('landing_site_name', sa.String(length=100), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('species_common', sa.String(length=100), nullable=False),
    sa.Column('species_local', sa.String(length=100), nullable=True),
    sa.Column('species_family', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('value_kes', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['landing_site_id'], ['landing_sites.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_landings_id'), 'historical_landings', ['id'], unique=False)
    op.create_index(op.f('ix_historical_landings_month'), 'historical_landings', ['month'], unique=False)
    op.create_index(op.f('ix_historical_landings_year'), 'historical_landings', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_landings_year'), table_name='historical_landings')
    op.drop_index(op.f('ix_historical_landings_month'), table_name='historical_landings')
    op.drop_index(op.f('ix_historical_landings_id'), table_name='historical_landings')
    op.drop_table('historical_landings')
    op.drop_index(op.f('ix_species_local_name'), table_name='species')
    op.drop_index(op.f('ix_species_id'), table_name='species')
    op.drop_index(op.f('ix_species_common_name'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_landing_sites_name'), table_name='landing_sites')
    op.drop_index(op.f('ix_landing_sites_id'), table_name='landing_sites')
    op.drop_table('landing_sites')
    # ### end Alembic commands ###
