"""Add lead_attributions table

Revision ID: bd0efaf9d933
Revises: 305f34d4a3c0
Create Date: 2026-07-06 12:02:06.979888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0efaf9d933'
down_revision: Union[str, Sequence[str], None] = '305f34d4a3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escrow_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('gross_amount_kes', sa.Float(), nullable=False),
    sa.Column('commission_kes', sa.Float(), nullable=True),
    sa.Column('net_to_seller_kes', sa.Float(), nullable=True),
    sa.Column('advance_paid_kes', sa.Float(), nullable=True),
    sa.Column('balance_to_release', sa.Float(), nullable=True),
    sa.Column('settlement_mode', sa.Enum('INSTANT', 'ESCROW', 'CREDIT', name='settlementmode'), nullable=True),
    sa.Column('payment_terms', sa.Enum('IMMEDIATE', 'NET_3', 'NET_7', 'NET_14', 'NET_30', 'NET_45', name='paymentterms'), nullable=True),
    sa.Column('status', sa.Enum('HELD', 'PARTIALLY_RELEASED', 'RELEASED', 'REFUNDED', 'DISPUTED', name='escrowstatus'), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verification_method', sa.String(), nullable=True),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_escrow_accounts_id'), 'escrow_accounts', ['id'], unique=False)
    op.create_table('fisher_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fisher_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('lot_value_kes', sa.Float(), nullable=False),
    sa.Column('advance_rate', sa.Float(), nullable=True),
    sa.Column('advance_amount_kes', sa.Float(), nullable=False),
    sa.Column('advance_fee_kes', sa.Float(), nullable=True),
    sa.Column('fee_rate', sa.Float(), nullable=True),
    sa.Column('recovered_kes', sa.Float(), nullable=True),
    sa.Column('outstanding_kes', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'DISBURSED', 'RECOVERING', 'RECOVERED', 'DEFAULTED', name='advancestatus'), nullable=True),
    sa.Column('mpesa_reference', sa.String(), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fisher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fisher_advances_id'), 'fisher_advances', ['id'], unique=False)
    op.create_table('lead_attributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=100), nullable=True),
    sa.Column('partner_code', sa.String(length=50), nullable=True),
    sa.Column('partner_campaign', sa.String(length=100), nullable=True),
    sa.Column('partner_referrer', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('landing_page', sa.String(length=200), nullable=True),
    sa.Column('registration_source', sa.String(length=30), nullable=True),
    sa.Column('device', sa.String(length=30), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('lead_name', sa.String(length=100), nullable=True),
    sa.Column('lead_phone', sa.String(length=20), nullable=True),
    sa.Column('lead_email', sa.String(length=200), nullable=True),
    sa.Column('lead_role', sa.String(length=50), nullable=True),
    sa.Column('lead_location', sa.String(length=200), nullable=True),
    sa.Column('lead_message', sa.Text(), nullable=True),
    sa.Column('converted_to_user', sa.Boolean(), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_order_id', sa.Integer(), nullable=True),
    sa.Column('first_visit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_visit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['converted_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_attributions_id'), 'lead_attributions', ['id'], unique=False)
    op.create_index(op.f('ix_lead_attributions_partner_code'), 'lead_attributions', ['partner_code'], unique=False)
    op.create_index(op.f('ix_lead_attributions_user_id'), 'lead_attributions', ['user_id'], unique=False)
    op.create_table('supplier_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_amount_kes', sa.Float(), nullable=False),
    sa.Column('paid_amount_kes', sa.Float(), nullable=True),
    sa.Column('outstanding_kes', sa.Float(), nullable=False),
    sa.Column('payment_terms', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agreed_payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'PROCESSING', 'PAID', 'PARTIAL', 'OVERDUE', name='supplierpaymentstatus'), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('mpesa_reference', sa.String(length=100), nullable=True),
    sa.Column('bank_reference', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=True),
    sa.Column('quality_grade', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_payments_id'), 'supplier_payments', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_reference'), 'supplier_payments', ['reference'], unique=True)
    op.create_table('trade_receivables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('gross_amount_kes', sa.Float(), nullable=False),
    sa.Column('vat_kes', sa.Float(), nullable=True),
    sa.Column('total_amount_kes', sa.Float(), nullable=False),
    sa.Column('paid_amount_kes', sa.Float(), nullable=True),
    sa.Column('outstanding_kes', sa.Float(), nullable=False),
    sa.Column('payment_terms', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('INVOICED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'DISPUTED', 'WRITTEN_OFF', name='receivablestatus'), nullable=True),
    sa.Column('delivery_confirmed', sa.Boolean(), nullable=True),
    sa.Column('delivery_confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('invoice_stamped', sa.Boolean(), nullable=True),
    sa.Column('etims_issued', sa.Boolean(), nullable=True),
    sa.Column('payment_method', sa.Enum('MPESA_PAYBILL', 'BANK_TRANSFER', 'PESA_LINK', 'CASH', 'CHEQUE', name='paymentmethod'), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_notes', sa.Text(), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=True),
    sa.Column('delivery_location', sa.String(length=200), nullable=True),
    sa.Column('received_by', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_receivables_id'), 'trade_receivables', ['id'], unique=False)
    op.create_index(op.f('ix_trade_receivables_invoice_number'), 'trade_receivables', ['invoice_number'], unique=True)
    op.drop_constraint(op.f('catch_drafts_reference_number_key'), 'catch_drafts', type_='unique')
    op.drop_index(op.f('ix_catch_drafts_reference_number'), table_name='catch_drafts')
    op.create_index(op.f('ix_catch_drafts_reference_number'), 'catch_drafts', ['reference_number'], unique=True)
    op.alter_column('quality_inspections', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PENDING', 'PASSED', 'FAILED', 'CONDITIONAL', name='inspectionstatus'),
               existing_nullable=True)
    op.alter_column('quality_inspections', 'grade',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.Enum('A', 'B', 'C', 'REJECTED', name='inspectiongrade'),
               existing_nullable=True)
    op.alter_column('quality_inspections', 'disposition',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('MARKETPLACE', 'DIRECT_SALE', 'PROCESSING_ONLY', 'RETURN_TO_FISHER', 'ANIMAL_FEED', 'DISPOSED', 'DONATED', name='lotdisposition'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quality_inspections', 'disposition',
               existing_type=sa.Enum('MARKETPLACE', 'DIRECT_SALE', 'PROCESSING_ONLY', 'RETURN_TO_FISHER', 'ANIMAL_FEED', 'DISPOSED', 'DONATED', name='lotdisposition'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('quality_inspections', 'grade',
               existing_type=sa.Enum('A', 'B', 'C', 'REJECTED', name='inspectiongrade'),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    op.alter_column('quality_inspections', 'status',
               existing_type=sa.Enum('PENDING', 'PASSED', 'FAILED', 'CONDITIONAL', name='inspectionstatus'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_index(op.f('ix_catch_drafts_reference_number'), table_name='catch_drafts')
    op.create_index(op.f('ix_catch_drafts_reference_number'), 'catch_drafts', ['reference_number'], unique=False)
    op.create_unique_constraint(op.f('catch_drafts_reference_number_key'), 'catch_drafts', ['reference_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trade_receivables_invoice_number'), table_name='trade_receivables')
    op.drop_index(op.f('ix_trade_receivables_id'), table_name='trade_receivables')
    op.drop_table('trade_receivables')
    op.drop_index(op.f('ix_supplier_payments_reference'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_id'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    op.drop_index(op.f('ix_lead_attributions_user_id'), table_name='lead_attributions')
    op.drop_index(op.f('ix_lead_attributions_partner_code'), table_name='lead_attributions')
    op.drop_index(op.f('ix_lead_attributions_id'), table_name='lead_attributions')
    op.drop_table('lead_attributions')
    op.drop_index(op.f('ix_fisher_advances_id'), table_name='fisher_advances')
    op.drop_table('fisher_advances')
    op.drop_index(op.f('ix_escrow_accounts_id'), table_name='escrow_accounts')
    op.drop_table('escrow_accounts')
    # ### end Alembic commands ###
