"""Add ESG models — CatchEvent, SpeciesSustainability, FisherImpact, TraceabilityChain, ComplianceDocument

Revision ID: bf76f89a252b
Revises: 5fdc9ef95e3d
Create Date: 2026-05-21 07:57:49.857612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf76f89a252b'
down_revision: Union[str, Sequence[str], None] = '5fdc9ef95e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_sustainability_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_name', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('local_names', sa.String(length=300), nullable=True),
    sa.Column('sustainability_status', sa.Enum('green', 'orange', 'red', 'unassessed', name='sustainabilitystatus'), nullable=False),
    sa.Column('sassi_rating', sa.String(length=20), nullable=True),
    sa.Column('iucn_status', sa.String(length=50), nullable=True),
    sa.Column('minimum_size_cm', sa.Float(), nullable=True),
    sa.Column('closed_season_start', sa.String(length=20), nullable=True),
    sa.Column('closed_season_end', sa.String(length=20), nullable=True),
    sa.Column('permitted_gear', sa.String(length=300), nullable=True),
    sa.Column('prohibited_gear', sa.String(length=300), nullable=True),
    sa.Column('export_permitted', sa.Boolean(), nullable=True),
    sa.Column('requires_permit', sa.Boolean(), nullable=True),
    sa.Column('habitat', sa.String(length=200), nullable=True),
    sa.Column('depth_range_m', sa.String(length=50), nullable=True),
    sa.Column('typical_price_range_kes', sa.String(length=50), nullable=True),
    sa.Column('premium_markets', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_sustainability_profiles_id'), 'species_sustainability_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_species_sustainability_profiles_species_name'), 'species_sustainability_profiles', ['species_name'], unique=True)
    op.create_table('fisher_impact_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fisher_id', sa.Integer(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('dependents_count', sa.Integer(), nullable=True),
    sa.Column('primary_income_source', sa.String(length=100), nullable=True),
    sa.Column('years_fishing', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('bmu_name', sa.String(length=100), nullable=True),
    sa.Column('bmu_membership_active', sa.Boolean(), nullable=True),
    sa.Column('cooperative_name', sa.String(length=100), nullable=True),
    sa.Column('cooperative_member', sa.Boolean(), nullable=True),
    sa.Column('owns_vessel', sa.Boolean(), nullable=True),
    sa.Column('vessel_count', sa.Integer(), nullable=True),
    sa.Column('has_cold_storage', sa.Boolean(), nullable=True),
    sa.Column('has_smartphone', sa.Boolean(), nullable=True),
    sa.Column('lifetime_catch_kg', sa.Float(), nullable=True),
    sa.Column('lifetime_earnings_kes', sa.Float(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=True),
    sa.Column('avg_monthly_earnings_kes', sa.Float(), nullable=True),
    sa.Column('last_transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_species', sa.String(length=200), nullable=True),
    sa.Column('has_life_jacket', sa.Boolean(), nullable=True),
    sa.Column('has_safety_training', sa.Boolean(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fisher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fisher_impact_profiles_fisher_id'), 'fisher_impact_profiles', ['fisher_id'], unique=True)
    op.create_index(op.f('ix_fisher_impact_profiles_id'), 'fisher_impact_profiles', ['id'], unique=False)
    op.create_table('catch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('fisher_id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('individual_count', sa.Integer(), nullable=True),
    sa.Column('catch_method', sa.Enum('handline', 'longline', 'trap', 'gillnet', 'purse_seine', 'spear', 'beach_seine', 'cast_net', 'trawl', 'diving', 'gleaning', 'other', name='catchmethod'), nullable=True),
    sa.Column('gear_type', sa.String(length=100), nullable=True),
    sa.Column('gear_details', sa.String(length=200), nullable=True),
    sa.Column('landing_site', sa.String(length=100), nullable=False),
    sa.Column('bmu_reference', sa.String(length=100), nullable=True),
    sa.Column('landing_officer', sa.String(length=100), nullable=True),
    sa.Column('catch_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('landing_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fishing_ground', sa.String(length=200), nullable=True),
    sa.Column('gps_lat_catch', sa.Float(), nullable=True),
    sa.Column('gps_lng_catch', sa.Float(), nullable=True),
    sa.Column('vessel_reg', sa.String(length=50), nullable=True),
    sa.Column('vessel_name', sa.String(length=100), nullable=True),
    sa.Column('vessel_size_category', sa.Enum('canoe', 'small_motorised', 'medium', 'large', 'industrial', name='vesselsizecategory'), nullable=True),
    sa.Column('crew_size', sa.Integer(), nullable=True),
    sa.Column('trip_duration_days', sa.Float(), nullable=True),
    sa.Column('female_crew_count', sa.Integer(), nullable=True),
    sa.Column('fishing_permit_no', sa.String(length=100), nullable=True),
    sa.Column('permit_expiry_date', sa.String(length=20), nullable=True),
    sa.Column('is_cross_border', sa.Boolean(), nullable=True),
    sa.Column('origin_country', sa.String(length=50), nullable=True),
    sa.Column('iuu_risk_level', sa.Enum('low', 'medium', 'high', 'flagged', 'unknown', name='iuurisklevel'), nullable=True),
    sa.Column('iuu_risk_notes', sa.Text(), nullable=True),
    sa.Column('temperature_at_landing_celsius', sa.Float(), nullable=True),
    sa.Column('ice_used', sa.Boolean(), nullable=True),
    sa.Column('ice_kg', sa.Float(), nullable=True),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verification_method', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fisher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catch_events_fisher_id'), 'catch_events', ['fisher_id'], unique=False)
    op.create_index(op.f('ix_catch_events_id'), 'catch_events', ['id'], unique=False)
    op.create_index(op.f('ix_catch_events_landing_site'), 'catch_events', ['landing_site'], unique=False)
    op.create_index(op.f('ix_catch_events_lot_id'), 'catch_events', ['lot_id'], unique=False)
    op.create_index(op.f('ix_catch_events_species'), 'catch_events', ['species'], unique=False)
    op.create_index(op.f('ix_catch_events_vessel_reg'), 'catch_events', ['vessel_reg'], unique=False)
    op.create_table('traceability_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_reference', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('catch_event_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('fisher_name', sa.String(length=100), nullable=True),
    sa.Column('fisher_id', sa.Integer(), nullable=True),
    sa.Column('landing_site', sa.String(length=100), nullable=True),
    sa.Column('catch_date', sa.String(length=20), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('quantity_kg', sa.Float(), nullable=True),
    sa.Column('buyer_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_date', sa.String(length=20), nullable=True),
    sa.Column('iuu_risk_level', sa.String(length=20), nullable=True),
    sa.Column('cold_chain_maintained', sa.Boolean(), nullable=True),
    sa.Column('permits_verified', sa.Boolean(), nullable=True),
    sa.Column('bmu_verified', sa.Boolean(), nullable=True),
    sa.Column('export_ready', sa.Boolean(), nullable=True),
    sa.Column('export_issues', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['catch_event_id'], ['catch_events.id'], ),
    sa.ForeignKeyConstraint(['fisher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traceability_chains_chain_reference'), 'traceability_chains', ['chain_reference'], unique=True)
    op.create_index(op.f('ix_traceability_chains_id'), 'traceability_chains', ['id'], unique=False)
    op.create_index(op.f('ix_traceability_chains_order_id'), 'traceability_chains', ['order_id'], unique=False)
    op.create_table('compliance_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_reference', sa.String(length=50), nullable=False),
    sa.Column('doc_type', sa.Enum('catch_certificate', 'kebs_export', 'eu_catch_certificate', 'health_certificate', 'eco_label', 'esg_report', 'haccp_record', 'fisher_earnings', 'impact_report', name='compliancedoctype'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('fisher_id', sa.Integer(), nullable=True),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_by', sa.String(length=100), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['traceability_chains.id'], ),
    sa.ForeignKeyConstraint(['fisher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['inventory_lots.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_documents_doc_reference'), 'compliance_documents', ['doc_reference'], unique=True)
    op.create_index(op.f('ix_compliance_documents_doc_type'), 'compliance_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_compliance_documents_id'), 'compliance_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_documents_id'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_doc_type'), table_name='compliance_documents')
    op.drop_index(op.f('ix_compliance_documents_doc_reference'), table_name='compliance_documents')
    op.drop_table('compliance_documents')
    op.drop_index(op.f('ix_traceability_chains_order_id'), table_name='traceability_chains')
    op.drop_index(op.f('ix_traceability_chains_id'), table_name='traceability_chains')
    op.drop_index(op.f('ix_traceability_chains_chain_reference'), table_name='traceability_chains')
    op.drop_table('traceability_chains')
    op.drop_index(op.f('ix_catch_events_vessel_reg'), table_name='catch_events')
    op.drop_index(op.f('ix_catch_events_species'), table_name='catch_events')
    op.drop_index(op.f('ix_catch_events_lot_id'), table_name='catch_events')
    op.drop_index(op.f('ix_catch_events_landing_site'), table_name='catch_events')
    op.drop_index(op.f('ix_catch_events_id'), table_name='catch_events')
    op.drop_index(op.f('ix_catch_events_fisher_id'), table_name='catch_events')
    op.drop_table('catch_events')
    op.drop_index(op.f('ix_fisher_impact_profiles_id'), table_name='fisher_impact_profiles')
    op.drop_index(op.f('ix_fisher_impact_profiles_fisher_id'), table_name='fisher_impact_profiles')
    op.drop_table('fisher_impact_profiles')
    op.drop_index(op.f('ix_species_sustainability_profiles_species_name'), table_name='species_sustainability_profiles')
    op.drop_index(op.f('ix_species_sustainability_profiles_id'), table_name='species_sustainability_profiles')
    op.drop_table('species_sustainability_profiles')
    # ### end Alembic commands ###
