"""Add escrow, fisher_advance, credit fields on user, payment terms on order

Revision ID: c760f4cebfe9
Revises: bb7ce0014f0c
Create Date: 2026-06-24 12:39:03.920540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c760f4cebfe9'
down_revision: Union[str, Sequence[str], None] = 'bb7ce0014f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_terms', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('settlement_mode', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('credit_score', sa.String(), nullable=True))
    op.add_column('users', sa.Column('payment_terms', sa.String(), nullable=True))
    op.add_column('users', sa.Column('outstanding_balance_kes', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('on_time_payment_rate', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('total_orders_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_orders_count')
    op.drop_column('users', 'on_time_payment_rate')
    op.drop_column('users', 'outstanding_balance_kes')
    op.drop_column('users', 'payment_terms')
    op.drop_column('users', 'credit_score')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'due_date')
    op.drop_column('orders', 'settlement_mode')
    op.drop_column('orders', 'payment_terms')
    # ### end Alembic commands ###
