"""Add inventory_lots and cold_storage_facilities tables

Revision ID: ce34d312b8cf
Revises: b352c6ff247e
Create Date: 2026-05-11 09:56:21.843013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce34d312b8cf'
down_revision: Union[str, Sequence[str], None] = 'b352c6ff247e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cold_storage_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('total_capacity_kg', sa.Float(), nullable=False),
    sa.Column('current_stock_kg', sa.Float(), nullable=False),
    sa.Column('temperature_min_c', sa.Float(), nullable=True),
    sa.Column('temperature_max_c', sa.Float(), nullable=True),
    sa.Column('storage_fee_per_kg_per_day', sa.Float(), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('manager_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cold_storage_facilities_id'), 'cold_storage_facilities', ['id'], unique=False)
    op.create_table('inventory_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=False),
    sa.Column('traceability_code', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('product_form', sa.Enum('WHOLE_UNGUTTED', 'WHOLE_GUTTED', 'HEADED_GUTTED', 'FILLET', 'DRIED', 'SMOKED', 'LIVE', 'OTHER', name='productform'), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('available_kg', sa.Float(), nullable=False),
    sa.Column('reserved_kg', sa.Float(), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'PENDING', name='qualitygrade'), nullable=False),
    sa.Column('condition', sa.Enum('FRESH', 'FROZEN', 'DRIED', 'LIVE', 'PROCESSED', name='lotcondition'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_user_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('landing_site', sa.String(length=50), nullable=False),
    sa.Column('bmu_reference', sa.String(length=100), nullable=True),
    sa.Column('catch_date', sa.String(length=20), nullable=True),
    sa.Column('landing_date', sa.String(length=20), nullable=True),
    sa.Column('vessel_name', sa.String(length=100), nullable=True),
    sa.Column('vessel_reg', sa.String(length=50), nullable=True),
    sa.Column('ownership_type', sa.Enum('MARKETPLACE', 'MARINECATCH_OWNED', 'CONSIGNMENT', 'CONTRACT_RESERVED', name='ownershiptype'), nullable=False),
    sa.Column('purchase_price_per_kg', sa.Float(), nullable=True),
    sa.Column('selling_price_per_kg', sa.Float(), nullable=False),
    sa.Column('min_price_per_kg', sa.Float(), nullable=True),
    sa.Column('cold_storage_fee_per_kg_per_day', sa.Float(), nullable=True),
    sa.Column('handling_fee_kes', sa.Float(), nullable=True),
    sa.Column('qa_fee_kes', sa.Float(), nullable=True),
    sa.Column('cold_storage_id', sa.Integer(), nullable=True),
    sa.Column('storage_location', sa.String(length=200), nullable=True),
    sa.Column('storage_entry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('storage_exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfillment_mode', sa.Enum('SELF_PICKUP', 'SELLER_DELIVERY', 'THIRD_PARTY_LOGISTICS', 'MARINECATCH_FULFILLMENT', name='fulfillmentmode'), nullable=True),
    sa.Column('logistics_responsibility', sa.Enum('BUYER', 'SELLER', 'MARINECATCH', 'THIRD_PARTY', name='logisticsresponsibility'), nullable=True),
    sa.ForeignKeyConstraint(['cold_storage_id'], ['cold_storage_facilities.id'], ),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traceability_code')
    )
    op.create_index(op.f('ix_inventory_lots_batch_number'), 'inventory_lots', ['batch_number'], unique=False)
    op.create_index(op.f('ix_inventory_lots_id'), 'inventory_lots', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_lots_landing_site'), 'inventory_lots', ['landing_site'], unique=False)
    op.create_index(op.f('ix_inventory_lots_lot_number'), 'inventory_lots', ['lot_number'], unique=True)
    op.create_index(op.f('ix_inventory_lots_ownership_type'), 'inventory_lots', ['ownership_type'], unique=False)
    op.create_index(op.f('ix_inventory_lots_species'), 'inventory_lots', ['species'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_lots_species'), table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_ownership_type'), table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_lot_number'), table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_landing_site'), table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_id'), table_name='inventory_lots')
    op.drop_index(op.f('ix_inventory_lots_batch_number'), table_name='inventory_lots')
    op.drop_table('inventory_lots')
    op.drop_index(op.f('ix_cold_storage_facilities_id'), table_name='cold_storage_facilities')
    op.drop_table('cold_storage_facilities')
    # ### end Alembic commands ###
