"""Add ESG fields, unique phone, gear type

Revision ID: f3c5a40f4c92
Revises: b38b05d847b8
Create Date: 2026-05-11 10:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c5a40f4c92'
down_revision: Union[str, Sequence[str], None] = 'b38b05d847b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add ESG fields to users table
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('bmu_membership_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('fishing_license_no', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('license_expiry_date', sa.String(length=20), nullable=True))
    
    # Add unique constraint on phone
    op.create_unique_constraint('uq_users_phone', 'users', ['phone'])
    
    # Add ESG fields to inventory_lots table
    op.add_column('inventory_lots', sa.Column('gear_type', sa.String(length=50), nullable=True))
    op.add_column('inventory_lots', sa.Column('iuu_risk_flag', sa.Boolean(), nullable=True))
    op.execute("UPDATE inventory_lots SET iuu_risk_flag = FALSE WHERE iuu_risk_flag IS NULL")
    op.alter_column('inventory_lots', 'iuu_risk_flag', nullable=False)
    op.add_column('inventory_lots', sa.Column('sustainability_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove ESG fields from inventory_lots
    op.drop_column('inventory_lots', 'sustainability_notes')
    op.drop_column('inventory_lots', 'iuu_risk_flag')
    op.drop_column('inventory_lots', 'gear_type')
    
    # Remove unique constraint on phone
    op.drop_constraint('uq_users_phone', 'users', type_='unique')
    
    # Remove ESG fields from users
    op.drop_column('users', 'license_expiry_date')
    op.drop_column('users', 'fishing_license_no')
    op.drop_column('users', 'bmu_membership_id')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###